### ISSUE TITLE
Flash messages breaks the menu

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-unhcr#12]
![ckan](https://user-images.githubusercontent.com/557395/36350197-2f1b6fe8-14a5-11e8-91ef-7b09599df58e.png)

**Comment by amercader** [comment]
Markup is defined [here](https://github.com/ckan/ckan/blob/master/ckan/templates/page.html#L23)

**Comment by smth** [comment]
Fixed with https://github.com/okfn/ckanext-unhcr/commit/66c91b69591a688fd78b3485ff95bd2e222551d2
