### ISSUE TITLE
Show Assigned to Me does not work if using user display name

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#121]
![Screenshot_2019-04-25 Data deposit - Data Containers - RIDL](https://user-images.githubusercontent.com/200230/56740879-105d6680-6772-11e9-979d-8669d76f79de.png)

![Screenshot_2019-04-25 Data deposit - Data Containers - RIDL(1)](https://user-images.githubusercontent.com/200230/56740887-13585700-6772-11e9-9e16-1ce3040921b8.png)

URL used is

https://ridl-uat.unhcr.org/data-container/data-deposit?curator_display_name=ckan_curator2

Not sure what fields are we indexing but we need to match what we index with what we query (display name, name , id etc)

**Comment by roll** [comment]
Fixed in https://github.com/okfn/ckanext-unhcr/commit/6f1bd07d9e88b4b15250de06934405c6ba3c30d2
