### ISSUE TITLE
Compute dataset fields depending on file fields asynchronously

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#15]
The approach described in #8, #9 and #11 won't work when creating the dataset via the UI (99.9% of the time), because we are creating the dataset in two stages, first the metadata and then the resource(s). When the resources are created we can not change dataset fields inside the validators.

Let's do something much more simpler, a [background job](http://docs.ckan.org/en/latest/maintaining/background-tasks.html) fired after dataset creation or update (creating or editing a resource calls `package_update`) that gets the dataset id, retrieves it and updates it with all the fields that depend on file values. There will be a delay to have these values filled but in most cases it should happen almost immediately.

Implementation:

* Write a job function that gets a dataset id:
  * Calls `package_show` to get the full details
  * Iterates over all resources (if any) and applies the different logic described in #8, #9 and #11 to calculate the values for `dataset_process_status`, `identifiability` and `date_range_start/end`.
  * Calls `package_update` to update the dataset
* Implement `IPackageController` [`after_create`](http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IPackageController.after_create) and `after_update` methods, and enqueue the above function passing the dataset id as parameter, eg

    ```python

    # IPackageController
    def after_create(self, context, data_dict):
         toolkit.enqueue_job(process_dataset_fields, [data_dict['id']])
  
```
* Hide these three fields from the dataset form, using [this preset](https://github.com/frictionlessdata/ckanext-validation/blob/master/ckanext/validation/examples/ckan_default_schema.json#L120). Right now the preset is defined in ckanext-validation, you can copy it to unhcr if you want.

**Comment by amercader** [comment]
@roll let me know if this makes sense. This should be much simpler than the previous specs

**Comment by roll** [comment]
@amercader 
Sounds good.
