### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-unhcr#16]
# Overview

For now, we don't run tests on CI. Also following steps at https://github.com/okfn/ckanext-unhcr#ckanext-unhcr doesn't work to run tests at least for me. 

So Travis setup will help with both actual testing and will show how to run tests for ckanext.

**Comment by amercader** [comment]
yes, we need tests. Let's start with the custom field logic ones. I can create an example test to get you started

**Comment by roll** [comment]
Could create something like requirements.dev.txt to provide a way to run tests in fresh venv? 

The exact way of writing nose tests should be trivial

**Comment by amercader** [comment]
The dev image has all dev-requirements installed. We have a problem with the test db setting being overriden: https://github.com/okfn/docker-ckan/issues/9

**Comment by amercader** [comment]
Done https://travis-ci.org/okfn/ckanext-unhcr
