### ISSUE TITLE
DataPusher error when POSTing to CKAN

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#171]
When trying to upload eg [this file](https://ridl.unhcr.org/dataset/unhcr-cmr-2015-sens-v1-2/resource/43af9047-32bd-441d-b3b6-c757dc12808a) to the DataStore with the DataPusher the process fails with the following:

![Screenshot_2019-05-24 Enquete Sens Dans Les Sites Amenages De refugies Centrafricains De La Region De L’est Et L’adamoua Au](https://user-images.githubusercontent.com/200230/58326871-56b7eb00-7e2e-11e9-8f33-4193f032dd02.png)

Looking at the DataPusher logs, when it tries to POST to `datastore_create` with the data it is returning a 400 error coming from the WAF. The file works fine on a local install.

Options: 
* Contact IT and try to sort out what happens
* Implement support for an internal URL that allows the datapusher container to query the ckan one directly (right now it uses `ckan.site_url`
* Switch to xloader

**Comment by chris48s** [comment]
I reckon this was probably fixed by https://github.com/okfn/docker-ckan-unhcr-aws/commit/dd7db47b67fe079a4c93f0e19de25a06ab44b579 ?

**Comment by amercader** [comment]
Yes, this can be closed
