### ISSUE TITLE
Can't import DDI files in development environment

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-unhcr#178]
# Overview

I've tried to import locally DDI files available on staging but CKAN show a validation error :
```
Errors were found in the XML file:

Keywords: unexpected choice "refugees"
```

**Comment by amercader** [comment]
Sorry, that's my fault. After the changes in the parsing of DDI files, the example files that we had don't work any more. Try this one:

[DDI_test_v2.zip](https://github.com/okfn/ckanext-unhcr/files/3296050/DDI_test_v2.zip)

**Comment by roll** [comment]
Thanks. Closing due to it's not a bug for the future use
