### ISSUE TITLE
Accessing RIDL API via R

### ISSUE THREAD

**Issue by Edouard-Legoupil** [okfn/ckanext-unhcr#185]
Hi - 

I would like to explore how to batch upload cross tabulations from surveys in the server (cf https://github.com/unhcr/koboloadeR/issues/12 )

Tried - 

`library('ckanr')`
`ckanr_setup(url = "https://ridl.unhcr.org", key = "mykey...")`
`library(httr)`
`set_config(authenticate(username, password)) # where I change with my user..`
`set_config(verbose())`
`package_list(as = "table")`

as explained here: https://github.com/ropensci/ckanr/issues/106

 I got 

> Error: 403 - Authorization Error - message Access denied: <function package_list at 0x7f606cff2320> requires an authenticated user

Am I missing something ?

Thanks!

**Comment by roll** [comment]
cc @amercader

**Comment by amercader** [comment]
@Edouard-Legoupil the API only uses the API key based authentication (using an HTTP header). This line `set_config(authenticate(username, password))` is used to handle HTTP Basic Authentication, which the RIDL site does not use. Can you try removing it to see if it is affecting the normal header based authentication?


To test that you are using the correct key you can do the same API call using curl or similar directly:

```
curl -H Authorization:your-api-key https://ridl.unhcr.org/api/action/package_list
```

Make sure to use the API key for the relevant site (eg not the UAT site).

**Comment by Edouard-Legoupil** [comment]
` curl -H Authorization:your-api-key https://ridl.unhcr.org/api/action/package_list `

is working as a command line.. so I have the right api-key

When removing the setconfig part - i.e.

`library('ckanr')`
`ckanr_setup(url = "https://ridl.unhcr.org", key = "mykey...")`
`package_list(as = "table")`

I still receive the same error

> Error: 403 - Authorization Error - message Access denied: <function package_list at 0x7f606cff2320> requires an authenticated user

Is it working on your side? 

FYI -- 
> sessionInfo(package = NULL)
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

**Comment by Edouard-Legoupil** [comment]
It looks like I can not use the API with header based authentication only with the api-key with ckanR (which is my use case...). 
From the different examples I saw, the api-key authentication is used only when creating packages not for simple consultations... 
if RIDL is using AI authentication, maybe there's a way to handle that with CKANR?

**Comment by amercader** [comment]
I'm not familiar with ckanr I'm afraid. It's unfortunate that it does not send the API key on each call as different instances might have different authorization scenarios like on RIDL case.

If you are familiar with R perhaps you can modify the low level functions used to perform requests to always include your API key: https://github.com/ropensci/ckanr/blob/8f2990da65b567c104be6c65c9a8a677d39ff40d/R/zzz.R

> if RIDL is using AI authentication, maybe there's a way to handle that with CKANR?
Sorry, I'm not sure what do you mean by AI authentication

**Comment by Edouard-Legoupil** [comment]
> if RIDL is using AI authentication, maybe there's a way to handle that with CKANR?
Sorry, I'm not sure what do you mean by AI authentication

Sorry I meant AD - Active Directory - 

I submitted a ticked: https://github.com/ropensci/ckanr/issues/124 

I do not know how to fix this? Can you help?

Thanks,
Edouard

**Comment by Edouard-Legoupil** [comment]
Hi - ckanr has been now updated to include api key in each function:
https://github.com/ropensci/ckanr/issues/124#issuecomment-513965124

I have tested but it's still not working - Can you have a look?

Thanks for your support

**Comment by Edouard-Legoupil** [comment]
Hi - Testing this again

> library('ckanr')
> ckanr_setup(url = "https://ridl.unhcr.org", key = "mykey")
> package_list(as = "table")
Error: 403 - Authorization Error
  message Access denied: Action package_list requires an authenticated user

**Comment by amercader** [comment]
Hi @Edouard-Legoupil did you have any luck accessing RIDL via R?

I just tried with the following environment and it worked fine for me:

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ckanr_0.5.0 DBI_1.1.0  
```

The commands I run:

```
> ckanr_setup(url='https://ridl.unhcr.org', key='XXXXXX')
> package_list(as="table")
 [1] "2018-asr-demographic-table"                                                                       
 [2] "2019-planning-figure-data-and-tables-24-sep-2019-update"                                          
 [3] "2019-planning-figure-variance-comparison-table-and-analysis"                                      
```

**Comment by Edouard-Legoupil** [comment]
Yes - it's working now! Not sure what happened..

Was reading the vignette: https://docs.ropensci.org/ckanr/articles/ckanr.html - but it does not give much details..

- **SEARCH**: For instance `package_list(as = "table")` give me only 31 records while the home page of RIDL referes to `182 datasets`. Also not sure why but I would expect that the following to give me many records (99 datasets found for "protection-monitoring" on RIDL..) but it does not... 
> out <- package_search(q = '*protection-monitoring*', rows = 2, as = "table")$results

- **DOWNLOAD**: Would you have a sample code snippet to download a dataset via the package (so that I can build fully reproducible Rmd reports plugged in RDIL API)?

- **UPLOAD**: Last, would also some tuto to upload a new dataset via the package (as for instance we have a regional dataset that we then split per country in order to push them to country specific container..). I guess I need to [create a package](https://docs.ropensci.org/ckanr/reference/package_create.html) and then [create a resource](https://docs.ropensci.org/ckanr/reference/resource_create.html)

Thanks a lot!!



Thanks a lot!
