### ISSUE TITLE
Request data container creation

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#19]
Administrators of an existing data container can request the creation of a children data container.

## Process overview

* Data Container Admins see a "Request Data Container" button in the Data Containers page
* This opens the same form as creating a new data container, but in the "Parent" field there are only available the data containers the user is an admin of. 
* When submitted, the data container is created, and the submitter is added as admin, but internally the data container is flagged as `approval_needed`, so no it's not visible in search results and datasets can not be assigned to them.
* Site administrators receive an email with a link to activate or delete the new data container
* In either case, the user that requested the data container receives an email with the outcome (approved or rejected)

## Implementation

- [x] Set `ckan.auth.user_create_organizations` to True
- [x] Override the core `organization_create` auth function, allowing it only to users that are admin of an organization (`IAuthFunctions`)
- [x] Override the core `organization_create` and `organization_update` actions via `IActions` with similar logic to [this plugin](https://github.com/ViderumGlobal/ckanext-iati/blob/master/ckanext/iati/logic/action.py#L60):
  - [x] Check if user is sysadmin, if so defer to the core action and create org normally
  - [x] Check if has access (`check_access`), if so override state to `approval_needed` before calling the core action.
  - [x] Notify sysadmins if necessary via email
  - [x] When the state is changed, notify original user via email
- [x] UI: Display a different button on data containers index template depending on whether a sysadmin or an org admin ("Request data container" if the latter)
- [x] UI: Display a notice in the org form if not a sysadmin ("This data container needs to be approved, etc"
- [x] Form: only display the organizations that the user has permission in the parent form (this might happen automatically)
- [x] Check that pending containers don't appear in searches, and that datasets can not be assigned to them

## Estimate

3-4 days

**Comment by roll** [comment]
@amercader 
I'm stuck here with an error I don't understand. As an experiment, I use the master to reproduce and this error still happens. Steps:
- add `CKAN__AUTH__USER_CREATE_ORGANIZATIONS=True` to `.dev.env`
- restart the docker compose up
- create a new user
- log in as the new user
- click on `Add data container`
- get an `Internal Error`

```
...
ckan-dev_1    | File '/srv/app/src/ckan/ckan/logic/auth/__init__.py', line 40 in get_group_object
ckan-dev_1    |   return _get_object(context, data_dict, 'group', 'Group')
ckan-dev_1    | File '/srv/app/src/ckan/ckan/logic/auth/__init__.py', line 22 in _get_object
ckan-dev_1    |   .format(class_name))
ckan-dev_1    | ValidationError: {'message': 'Missing id, can not get Group object'}
```

**Comment by amercader** [comment]
@roll, it might be because of the custom group types I'll have a look asap

**Comment by amercader** [comment]
@roll you can clone ckanext-scheming in the `src` folder and apply this patch for now. I'll submit a proper fix:

```diff
diff --git a/ckanext/scheming/templates/scheming/group/group_form.html b/ckanext/scheming/templates/scheming/group/group_form.html
index a4e8428..23ccfa9 100644
--- a/ckanext/scheming/templates/scheming/group/group_form.html
+++ b/ckanext/scheming/templates/scheming/group/group_form.html
@@ -15,9 +15,11 @@
 
     <div class="form-actions">
         {% block delete_button %}
-        {% if h.check_access('group_delete', {'id': data.id}) and action=='edit'  %}
-        {% set locale = h.dump_json({'content': _('Are you sure you want to delete this Group?')}) %}
-        <a class="btn btn-danger pull-left" href="{% url_for controller='group', action='delete', id=data.id %}" data-module="confirm-action" data-module-i18n="{{ locale }}">{% block delete_button_text %}{{ _('Delete') }}{% endblock %}</a>
+        {% if action == 'edit' %}
+          {% if h.check_access('group_delete', {'id': data.id}) and action=='edit'  %}
+            {% set locale = h.dump_json({'content': _('Are you sure you want to delete this Group?')}) %}
+            <a class="btn btn-danger pull-left" href="{% url_for controller='group', action='delete', id=data.id %}" data-module="confirm-action" data-module-i18n="{{ locale }}">{% block delete_button_text %}{{ _('Delete') }}{% endblock %}</a>
+          {% endif %}
         {% endif %}
         {% endblock %}
         <button class="btn btn-primary" name="save" type="submit">{% block save_text %}{{ _('Save Group') }}{% endblock %}</button>
diff --git a/ckanext/scheming/templates/scheming/organization/group_form.html b/ckanext/scheming/templates/scheming/organization/group_form.html
index b85bd9d..f9dc83b 100644
--- a/ckanext/scheming/templates/scheming/organization/group_form.html
+++ b/ckanext/scheming/templates/scheming/organization/group_form.html
@@ -15,9 +15,11 @@
 
     <div class="form-actions">
         {% block delete_button %}
-        {% if h.check_access('group_delete', {'id': data.id}) and action=='edit'  %}
-        {% set locale = h.dump_json({'content': _('Are you sure you want to delete this Organization?')}) %}
-        <a class="btn btn-danger pull-left" href="{% url_for controller='organization', action='delete', id=data.id %}" data-module="confirm-action" data-module-i18n="{{ locale }}">{% block delete_button_text %}{{ _('Delete') }}{% endblock %}</a>
+        {% if action == 'edit' %}
+          {% if h.check_access('group_delete', {'id': data.id}) and action=='edit'  %}
+            {% set locale = h.dump_json({'content': _('Are you sure you want to delete this Organization?')}) %}
+            <a class="btn btn-danger pull-left" href="{% url_for controller='organization', action='delete', id=data.id %}" data-module="confirm-action" data-module-i18n="{{ locale }}">{% block delete_button_text %}{{ _('Delete') }}{% endblock %}</a>
+          {% endif %}
         {% endif %}
         {% endblock %}
         <button class="btn btn-primary" name="save" type="submit">{% block save_text %}{{ _('Save Organization') }}{% endblock %}</button>


```

**Comment by roll** [comment]
@amercader 
Thanks. It works.
