### ISSUE TITLE
Wrong URL when creating/updating resources

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#196]
At some point during the post-processing (background jobs) done when creating a dataset some resource URLs are set to http://<filename> (or just <filename>)

See eg: https://ridl.unhcr.org/dataset/unhcr-cmr-2017-lis-1-1

This is probably caused by different jobs modifying the dataset at the same time. We need to investigate more.

**Comment by roll** [comment]
@amercader 
I checked this out:
- I can reproduce it locally
- it seems happened only for one dataset on production (randomly checked the others)
- I don't see we have code in the jobs messing with resources' urls - https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/jobs.py
