### ISSUE TITLE
Enable ckanext-validation

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#2]
This is a good easy task to familiarize yourself with the deployment scripts @roll.

We basically just need to install and enable ckanext-validation with the default settings, check that it works and document it on the user guide.

Tasks:

- [x] Install ckanext-validation (on [`ckan/Dockerfile`](https://github.com/okfn/docker-ckan-unhcr/blob/master/ckan/Dockerfile) and [`ckan/Dockerfile.dev`](https://github.com/okfn/docker-ckan-unhcr/blob/master/ckan/Dockerfile.dev) and add it to `CKAN__PLUGINS` in `.web.env` (I don't think we need extra configuration options but if necessary add any `CKANEXT__VALIDATION__*` one we need)
- [x] Check the extension works on our setup. Validation is run asynchronously when you upload a tabular file. If working [a badge](https://github.com/frictionlessdata/ckanext-validation#overview) should appear next to the resource list. The logs should show if the jobs are being run (the worker is already configured in the images)
- [x] Add a small section about data validation in the User Guide.

**Comment by roll** [comment]
@amercader 
I was partially able to install it, but I have some questions.

---

I've tried everything but it seems `ckanext-validation` should use the following `paster` command instead of readme's one (without `--plugin`). I searched it in the `ckanext-validation` repo and it works (though I don't know how `paster` plugins work):

```
paster --plugin=ckanext-validation validation init-db -c ${CKAN_INI} # also path changed to env var
```

---

Before I've realized that it should be added to the extension docker installation the extension was successfully built but wasn't working (with obvious reasons - no required database table). But having this `paster` command now my docker build is failing with:

```
sqlalchemy.exc.OperationalError: (OperationalError) could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Network unreachable
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
 None None
```
So it's easy to say that the extension can't connect to the database to create `validation`/etc relation. But I don't know for now how to point the extension to use a database described in `.env`.

---

Also, a question related to the workflow. To install the extension I modify `docker-ckan` repository code. But our working repository is `ckanext-unhcr`. So how we should store/track these changes to preserve as a part of the project?

**Comment by amercader** [comment]
@roll regarding your second question, the deployment repo that you should use is [`docker-ckan-unhcr`](https://github.com/okfn/docker-ckan-unhcr), not `docker-ckan`, as it is one tailored to the project with secrets and extension. I think is fine to keep this separated from ckanext-unhcr as they server two different purposes and the deployment should not be updated that often when we start working.

Regarding your first one, the database won't be available at build time, any setup operations that relies on the database should be done at run time. The setup script is defined with the `CMD` command in the Dockerfile. Right now we have [`start_ckan.sh`](https://github.com/okfn/docker-ckan-unhcr/blob/master/ckan-base/Dockerfile#L96) for the production images and `start_ckan_development.sh` for the development ones. These scripts call [`prerun.py`](https://github.com/okfn/docker-ckan-unhcr/blob/master/ckan-base/setup/prerun.py), which is the one that handles complex commands like initialize the db. Because of how docker compose works we can't be sure that the database container will be ready when this is executed, that's why there is some logic there to wait until it is. Initializing the validation tables should be done at this point.

The easiest option is to override the `CMD` in our custom [`ckan`](https://github.com/okfn/docker-ckan-unhcr/tree/master/ckan) images and use a custom `prerun_unhcr.py` that initializes the tables after `prerun.py` is executed.
This will mean duplicating code so the best solution would be to add some mechanism in the base images (`ckan-base` and `ckan-dev`) to allow custom scripts in child images (like the scripts in `docker-entrypoint-initdb.d` for the [postgres](https://hub.docker.com/_/postgres/) image). I'll create an issue for that in the main deployment repo, but for now let's do the previous option.

If you don't want to bother with this for now just create the tables on the running container using:

```
docker-compose -f docker-compose.dev.yml exec ckan-dev paster --plugin=ckanext-validation validation init-db -c ${CKAN_INI} 
```

**Comment by amercader** [comment]
Added an issue for the proper fix here https://github.com/okfn/docker-ckan/issues/10

**Comment by roll** [comment]
@amercader 
Because you've posted here the third link to the non-existent repo (`docker-ckan-unchr`) I'm starting to suspect that there is some kind of private repo I don't have access to :smiley:  At first place I thought it was a typo.

**Comment by pwalsh** [comment]
@roll I gave you access now

**Comment by roll** [comment]
@pwalsh 
Thanks

**Comment by amercader** [comment]
Sorry @roll, I thought you had access :sweat:

**Comment by roll** [comment]
@amercader 
No worries. I was good to me to spend a few hours on the default one to learn it.

**Comment by roll** [comment]
DONE
