### ISSUE TITLE
Prevent access to datasets to non-logged in users

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#20]
## Overview

Datasets can only be "Internally visible" or "Private". "Internally visible" means that you need to be logged in to see them.

In practice this means requiring a logged in user for pretty much any action in `get.py`. The only thing that will be available by default will be the home page and about / help pages if any.
We could display the data containers tree but it doesn't make much sense as when clicking on a data container you won't be able to see any datasets. (TODO: confirm this)

## Implementation

* Extend auth functions to prevent anonymous access (Using the `toolkit.auth_disallow_anonymous_access` decorator or checking for context['user']). At least we should cover `package_search`, `package_show`, `organization_show` and `group_show`
* Catch Authorization errors and display a notice on the UI: You need to login to see this. In some cases like the search page we need to override the core controller with our own (`IRoutes`) because Auth e
xceptions are not catched. In others like on the dataset page we might need to override the error template (`error_document_template.html`)

## Estimate

2 days

**Comment by amercader** [comment]
@smth has added changes in the `page.html` template to display a Log In button to non-logged in users. We need to:

- [ ] Add actual link
- [ ] Add exceptions: login page :), reset password page

@smth I'll do this, just adding this so I remember.

**Comment by smth** [comment]
I thought it was stated previously that there would be no login form on the
site. If that's not the case, the button could be replaced with the form.
