### ISSUE TITLE
"No data container" option showing up on dataset form

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#247]
All datasets should belong to a Data Container.
Check the auth configuration.

**Comment by roll** [comment]
@amercader 
If you remember - https://github.com/okfn/docker-ckan-unhcr/blob/bb9cbd9c872c3f06d6d98ed0f88938c15279303d/.dev.env#L47-L49

I added it because we'd had some problem (we can check the blame to see the reason/maybe no actual to 2.8)

**Comment by amercader** [comment]
Yes, that is probably the wrong approach. I think we should keep the default values for these options and handle the data deposit case separately
