### ISSUE TITLE
Broken DDI import on CKAN 2.8

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#250]
The UI is broken and the actual import fails with an error.

![Screenshot_2019-12-12 Create Dataset - RIDL](https://user-images.githubusercontent.com/200230/70705481-6ddbfe80-1cd4-11ea-9b1a-4c353402f716.png)

**Comment by roll** [comment]
@amercader 
So I've investigated the problem:

- the UI is broken probably after the BS3 migration because I had it tested for ckan2.8
- there is no regression in the functionality itself. I was able to import DDI Test File locally and on staging
- the `bo-amman-test` file fails with `import: Dataset import from XML failed: Unicode strings with encoding declaration are not supported.` wich seems to be a separate issue or limitation of DDI

**Comment by amercader** [comment]
@roll I think this should fix it (in ckanext-ddi). Can you check locally and if so push and tag a new release, update docker-ckan-unhcr?

```diff
diff --git a/ckanext/ddi/fanstatic/upload.js b/ckanext/ddi/fanstatic/upload.js
index 69d8d72..fbbe86a 100644
--- a/ckanext/ddi/fanstatic/upload.js
+++ b/ckanext/ddi/fanstatic/upload.js
@@ -36,8 +36,8 @@ this.ckan.module('file-upload', function($) {
       var field_name = 'input[name="' + options.field_name + '"]';
 
       this.input = $(field_upload, this.el);
-      this.field_url = $(field_url, this.el).parents('.control-group');
-      this.field_image = this.input.parents('.control-group');
+      this.field_url = $(field_url, this.el).parents('.form-group');
+      this.field_image = this.input.parents('.form-group');
       this.field_url_input = $('input', this.field_url);
       this.field_name = this.el.parents('form').find(field_name);
       // this is the location for the upload/link data/image label
@@ -48,7 +48,7 @@ this.ckan.module('file-upload', function($) {
       // Is there a clear checkbox on the form already?
       var checkbox = $(field_clear, this.el);
       if (checkbox.length > 0) {
-        checkbox.parents('.control-group').remove();
+        checkbox.parents('.form-group').remove();
       }
 
       // Adds the hidden clear input to the form

```

**Comment by roll** [comment]
Done ddi@1.0.13
