### ISSUE TITLE
Misaligned data container tags field

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#255]
![Screenshot_2019-12-19 Edit - Africa - Data Containers - RIDL](https://user-images.githubusercontent.com/200230/71171494-359d6880-225e-11ea-8e96-8ce5a9d46247.png)

We just need to replicate the changes done to fix the dataset tags one: https://github.com/okfn/ckanext-unhcr/commit/653bebf6b2d5265b285ea9959a029973744323d0

**Comment by roll** [comment]
Fixed in a9adc87d9e16953de2ac6680e4d28fb24209f43e
