### ISSUE TITLE
Enable SAML2 authentication on the AWS sandbox site

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#259]
## Tasks

- [ ] Install and configure ckanext-saml2 as in the current images
- [ ] We need to ask for a new Azure AD application for our AWS site, and its metadata file, which is what we need to ship with our image. The file should be in [this folder](https://github.com/okfn/docker-ckan-unhcr/tree/master/ckan/saml2) and be called something like `idp_aws_sandbox.xml`. We then will need to add an env var `RIDL_ENV=aws_sandbox` present (check the docker-ckan-unchr Dockerfile)

**Comment by amercader** [comment]
@roll To enable SAML2 we might be required to run http://ridl.openknowledge.io/ under HTTPS. Do you know if that would be easy? perhaps via cloudflare or on AWS directly. 
Another option is to ask for a new unhcr domain, like ridl-sandbox.unhcr.org that they manage and run under SSL. But then I imagine that there would be some integration needed in our CDK stack to point the domain to the right place (related to #243)

**Comment by roll** [comment]
DONE
