### ISSUE TITLE
Investigate CDK WAF

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-unhcr#262]

**Comment by roll** [comment]
@amercader 
I've added a task here regarding WAF - https://github.com/okfn/ckanext-unhcr/issues/254

I'm closing this issue as I've investigated it:
- the CDK module is experimental stage now (not stable)
- there is 0 documentation with usage examples etc
- I didn't find any connection to e.g. load balancer CDK API or something like this
- I think the `firewall` stack has to be written by some security specialists with WAF experience because the CDK's API is hard-to-understand for a newcomer (I'm not sure what all these constructs do. Probably I would've understood If I'd worked with WAF)

**Comment by roll** [comment]
Of course, we can learn WAF to write CDK but it will take days

**Comment by amercader** [comment]
Thanks @roll, that's helpful. Just one question

> the CDK module is experimental stage now (not stable)
Do you mean the CDK module for WAF, or CDK in general?

**Comment by roll** [comment]
@amercader 
The WAF module - https://docs.aws.amazon.com/cdk/api/latest/docs/aws-waf-readme.html

All main modules like rds, vpc etc are stable
