### ISSUE TITLE
[Meta] Metrics dashboard page

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#264]
This is a meta-issue containing and overview of the Metrics dashboard features (not to be confused with the existing user dashboard). The goal is to provide maintainers with a clearer picture of how users interact with the portal and publish data on it by having a dedicated page that shows various metrics and visualizations.

![mockup_dashboard](https://user-images.githubusercontent.com/200230/76509089-bd56d580-644f-11ea-9687-1e9c7cc3c1ed.png)
(This is just a rough mockup)

Prior work that we might take inspiration from:

* CKAN core has a very basic `stats` plugin that displays some metrics: https://demo.ckan.org/stats
* [Humanitarian Data Exchange](https://data.humdata.org/group/ssd) has always done a great job of showing indicators on the UI
* [ckanext-report](https://github.com/davidread/ckanext-report) has a modular approach to generating and registering individual reports that might be interesting to look at (probably not for an initial stage)
* [WPRDC](http://www.wprdc.org/) dashboard: http://tools.wprdc.org/analytics/wprdc-dashboard/ External tool with loads of indicators about the CKAN site (currently down)
* [ckanext-dashboard](https://github.com/ckan/ckanext-dashboard) is an old extension that created a resource view combining other individual views (charts, tables, etc). It's not what we need but maybe there's something we can reuse there.

Given that the actual requirements are a bit unclear we should aim to build the page incrementally, starting with easy to get metrics and adding more complex ones later on.

This sounds like the kind of feature that could be built as a reusable standalone extension that other extensions can extend, but for the first iteration let's keep it in ckanext-unhcr.

Tasks:
TODO

**Comment by chris48s** [comment]
I'm going to close this issue.

Now that we've delivered a first iteration and we've got some more features to be added to it in the next release, further work on this topic is best handled as more specific issues "add a chart for A", etc
