### ISSUE TITLE
Create blueprint and template for metrics dashboard

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#265]
Create a new blueprint that renders a template for the metrics dashboard. 
The extension currently has Pylons controllers because we needed to extend the core dataset and organization ones, but this is a separate endpoint so let's use Flask based blueprints.

- [ ] Add a new `blueprints.py` module with a Blueprint that registers a `/metrics` (or `/site-dashboard`, anything but `/dashboard`) ([example](https://github.com/ckan/ckanext-dcat/blob/master/ckanext/dcat/blueprints.py))
- [ ] Create a new template and render it from the view function above. For the first version we can include easy stuff like:
* Number of datasets (`package_search`)
* Number of data containers (`organization_list`)
* Number of users on the site (`user_list`)
- [ ] Using `IBlueprint` register the new blueprint in `plugin.py`

**Comment by chris48s** [comment]
Going to close this one as we've got the basics in place now. Lets treat further "add a table/graph for X" as new issues
