### ISSUE TITLE
Store number of downloads

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#269]
One of the next requirements for metrics will be around reporting the number of downloads:

- Most downloaded datasets (datasets ranked by downloads)
- Most active users (users ranked by downloads)

Currently we don't track this so the first step is to work out the best way to log this information before we can report it.

**Comment by amercader** [comment]
Aside from the metrics needed by the dashboard there is also a requirements for admins to be able to track who downloaded individual resources so I'd like to try an use activities to track downloads as well.

Be warned, it's quite hacky, but activities on CKAN 2.8 are messy :)

In summary we need to create a custom activity at the time a user requests a file to download. That is the `/dataset/<id>/resource/<resource_id>/download` endpoint, which in our case we are already overriding ([route definition](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/plugin.py#L117), [controller](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/controllers/extended_package.py#L105). Once the activities are created we can query the relevant type to get the counts needed for the metrics dashboard, or implement custom activity streams for authorized users (downloads should not be mixed with the public activities).

A comment on our custom download endpoint. Right now it only handles the default local storage backend for file uploads, but once we move to AWS we are going to switch to ckanext-cloudstorage, which has its own overriden endpoint. So we'll need to defer to their one, but let's cross that bridge when we get there.

We'll focus first on storing the activities and retrieving any counts you need for the metrics.

* Call `activity_create` on the download endpoint using the logged in user id, the dataset id and the UTC timestamp, with a custom `activity_type` like `download resource`.
* Filter out `download resource` activities from the default returned activities by `*_activity_list` functions. We are already doing this for curation related activities, so it's just a matter to add a further filter. See functions starting [here](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/actions.py#L254)
* At this point you should have activities stored in the DB, so you can retrieve what you need either via actions (`activity_list`) or more likely via a bespoke DB query (it will be more performant).

I'll share existing code that should help with this.

**Comment by chris48s** [comment]
- [x] Log resource downloads using an activity when using `ckanext.unhcr.controllers.extended_package:ExtendedPackageController`: https://github.com/okfn/ckanext-unhcr/pull/280
- [x] Use custom activity to produce tables on the metrics dashboard: https://github.com/okfn/ckanext-unhcr/pull/281
- [ ] Log resource downloads using an activity when using `ckanext.cloudstorage.controller:StorageController`
- [ ] Additional reporting of downloads by dataset/user for admins: I haven't really got a handle on how we're going to surface this elsewhere yet. Are we going to use the existing activity streams and implement an activity renderer for 'download resource'? Are we going to do something bespoke?

**Comment by chris48s** [comment]
I think the remaining two points on this issue are now covered by https://github.com/okfn/ckanext-unhcr/pull/289 (cloudstorage) and https://github.com/okfn/ckanext-unhcr/issues/284 (activity streams) so I'm going to close this issue.
