### ISSUE TITLE
/datasets includes data deposits

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#292]
From google doc - **@amercader wrote:**
> I don't think search results should combine normal datasets and deposited datasets. Only normal ones should be shown. Or if both are shown they should be clearly labelled and you should be able to filter them. But we can confirm with them.

At the moment, `/dataset` exposes both datasets and deposits. It is possible to filter this, but the filter is not exposed to the user in a nice way. For example, we use this property in the summary emails:

https://github.com/okfn/ckanext-unhcr/blob/9a1cd68d4ae39340280e4027bb2915df1c97fb8e/ckanext/unhcr/mailer.py#L141-L158

If we don't want to totally lose that ability, maybe we could expose the `type` filter via the UI and make `-type:deposited-dataset` the default behaviour..

**Comment by chris48s** [comment]
It looks like the default behaviour of CKAN should be that if `ckan.search.show_all_types` is not set (which it is not in our case), only records where `type='dataset'` get returned when searching.

Stepping through the code in CKAN core, when we get to https://github.com/ckan/ckan/blob/9c595653b145530afe0839483ee7f6c4f86687ef/ckan/controllers/package.py#L249-L251

```
search_all==True
package_type=='dataset'
search_all_type=='dataset'
```

so we never append `+dataset_type:{type}` to the query.

Not sure where to go with it next..

**Comment by amercader** [comment]
This is totally a bug in CKAN core. The default [here](https://github.com/ckan/ckan/blob/master/ckan/controllers/package.py#L232:L233) should be `False`, not `dataset`.
Can you submit a PR on CKAN core? with separate commit for the dataset blueprint and package controller please, so it's easy to backport.
In the meantime you can add a patch to our own CKAN.

**Comment by chris48s** [comment]
I'm going to close this as it is now fixed on RIDL after https://github.com/okfn/docker-ckan-unhcr-aws/pull/30
