### ISSUE TITLE
Collapse facet lists in dataset page by default

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#31]
Add some JS to expand / collapse facet lists ([core template](https://github.com/ckan/ckan/blob/master/ckan/templates/snippets/facet_list.html)). Start collapsed by default, maybe leave the first one expanded.

**Comment by smth** [comment]
I've made a new extension for this https://github.com/okfn/ckanext-facetcollapse I still need to test and style for use with unhcr.

**Comment by smth** [comment]
Styling now [added](https://github.com/okfn/ckanext-unhcr/compare/theme).
