### ISSUE TITLE
Remove social sharing buttons in dataset page

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#32]

**Comment by smth** [comment]
Done in https://github.com/okfn/ckanext-unhcr/commit/1555c66e8c986847a88817791af2fc97f6e47881. Are they to stay on the resource page?

**Comment by amercader** [comment]
no, they need to be removed everywhere

**Comment by smth** [comment]
OK, I have removed them from the resource page (https://github.com/okfn/ckanext-unhcr/commit/3e32458b1d54aec3d7278f1b39db3eddb1e4408f), so I think that's everywhere.
