### ISSUE TITLE
Add the count of containers to the Manage Membership page

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#346]
![Screenshot_2020-06-25 Manage Membership - RIDL](https://user-images.githubusercontent.com/200230/85689737-2eef2280-b6d3-11ea-8621-e6e391ad0071.png)

**Comment by chris48s** [comment]
one line summary by role on the "Current Containers" line
e.g: admin=4, member=6

url: `data-container/membership`
