### ISSUE TITLE
Problem updating resource metadata

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#355]
"I have noticed that I am not able to modify a data resource metadata without uploading again the file. So I cannot update something quick, for example the description, without removing and uploading the file again. I don't know if it is an issue or by design, or if I am doing anything wrong. 
For example: https://ridl.unhcr.org/dataset/protection-monitoring-colombia-2018-2020/resource_edit/31042c78-fdef-4ba8-b43d-bcb6d1c72c68 , I click on  update resource button I receive this notification :" 
![ridl](https://user-images.githubusercontent.com/3184712/86017234-1610a500-ba24-11ea-9955-20654fe70091.png)

**Comment by chris48s** [comment]
Good news: This issue is already fixed in version 1.5.0 (the release currently deployed on UAT)
That can be deployed to Production whenever you are ready.

**Comment by chris48s** [comment]
this fix is deployed to production now
