### ISSUE TITLE
Save and Add or Finish button mishap

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#357]
It seems that if a user accidentally clicks on 'Save and Add', instead of 'Finish' when uploading resources to a dataset, there's no way to rectify the mistake. Going back using the browsers Back button results in problems, and there's no option to cancel the upload resource form - or at least not an evident and user-friendly option.

**Comment by chris48s** [comment]
Provide a notification during the creation process that draft datasets can be viewed at https://localhost:5000/dashboard/datasets and published
Text TBC
