### ISSUE TITLE
Resource size limitations

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#361]
Could we make size limitations more apparent for users? Ideally, this would come dynamically from a config file, so we don't have to modify it if we ever change the file upload limit.

**Comment by chris48s** [comment]
@amercader - do we actually impose a hard limit on resource size, or are there practical limitations (e.g: if the upload request doesn't complete within X seconds, it will time out)?

**Comment by amercader** [comment]
@chris48s There is a config option at the [CKAN level](https://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-max-resource-size). It is currently set at [100 Mb](https://github.com/okfn/docker-ckan-unhcr-aws/blob/b1fbf52e9a6e8e48a567e82cd807858537a53d64/ckan/environment/base.env#L12).
I don't think it's relevant in our case but if CKAN sits behind Nginx there's anothe option you need to tweak at that level to allow paylods bigger than nginx default.
