### ISSUE TITLE
Helper text for dataset title

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#362]
Could we add more information on naming conventions? Like so: 'CommissioningOrganization_ISOCode_Year_datasetname_version'

**Comment by chris48s** [comment]
On hold pending more discussion with curation team

**Comment by mariannurban** [comment]
Could we please use the following sentence?
Please make sure to include the following information in the order indicated: 'Survey name/title', 'Location', 'Country', 'Year(s)'.

**Comment by chris48s** [comment]
That exact wording is going to be a bit long

![Screenshot at 2020-07-28 09-03-21](https://user-images.githubusercontent.com/6025893/88638011-cf5dab80-d0b2-11ea-8287-7f99a2f627a7.png)

but I've submitted a PR for a shortened version :+1:
