### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#380]
Make the link to the user guide at im.unhcr.org/ridl available on the interface of RIDL

**Comment by mariannurban** [comment]
Could we please change the sentence to: 
'More guidance on how to use RIDL is available here'.
I'm also wondering if we could put this link to more places on the site...will come back with suggestions.

**Comment by chris48s** [comment]
We usually deliver context-sensitive help in the sidebar on the left. We could maybe always have a link to the user guide in the sidebar

Another option would be to add a menu item for it e.g:

![Screenshot at 2020-07-27 17-00-22](https://user-images.githubusercontent.com/6025893/88564209-d7720880-d02a-11ea-94d9-7c736a2971ad.png)

**Comment by mariannurban** [comment]
I like both ideas! The only suggestion I would have is that on the Data Deposit pages, maybe we could display the direct link to the DD user guide pdf?
