### ISSUE TITLE
Rename organizations to Data Containers

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#4]
This can be done at different levels.

- [x] The most important one is changing mentions of "Organization" to "Data Container" in the UI and all the user facing strings. To do so we will use a [custom translation](http://docs.ckan.org/en/latest/extensions/translating-extensions.html) in our extension that replaces all the terms.
- [x] Replace `/organization/` routes with `/data-container/` ones. This means
   * duplicating all `/organization/` routes in core with `/data-container/` equivalent in ckanext-unhcr with `IRoutes` (can we use a hack to iterate over existing routes and change them on the fly?, if not we will have to duplicate them)
   * Update the links in all templates

**Comment by amercader** [comment]
@smth The rename has messed with the top menu

![2018-02-12-17-32-193 134 241 126](https://user-images.githubusercontent.com/200230/36107623-f36c81dc-101a-11e8-8fc8-3127de0364de.png)

**Comment by smth** [comment]
Yeah, I thought it might, but have been anticipating that we may get rid of Groups and/or About. Are we keeping all four items?

**Comment by smth** [comment]
The "Create a new data container" button on dataset/new currently points to organization/new

**Comment by roll** [comment]
- [ ] If we delete a data container a flash message says that the **organization** has been deleted.

**Comment by amercader** [comment]
I get data container. Perhaps you were deleting an old data container that still had the organization type internally?
![screenshot-2018-4-27 data containers - ckan](https://user-images.githubusercontent.com/200230/39357070-fe18d55a-4a11-11e8-9706-6b60a4447293.png)

It's not a big deal anyway

**Comment by roll** [comment]
@amercader 
My bad - it's a confirmation modal (not a big deal too)

```
Please Confirm Action
Are you sure you want to delete this Organization?
```

**Comment by amercader** [comment]
cool, I fixed that
