### ISSUE TITLE
Example of file uploading on RIDL using APIs.

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#431]
"We received more than 100 SENS datasets, so this could make the upload so much quicker.

As said, I am able to create a data resource or attachment with its metadata, but not to upload a file for the resource (I can only upload it later using the web interface). I am also able to set a link to a file, but not doing the actual upload to our RIDL.

It would be great if a working example could be provided. Any language is welcome: Python, R, Ruby, etc."

**Comment by amercader** [comment]
Here is a gist with a couple of working examples: https://gist.github.com/amercader/10571a94f37ed63b51360351836437ad
