### ISSUE TITLE
Regenerating API key results in error

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#432]
![image](https://user-images.githubusercontent.com/3184712/98925993-05defb00-24d7-11eb-8fc5-f5beda8f3d98.png)

Tested with my user urbanm and eksi.

**Comment by amercader** [comment]
@chris48s This can be reproduced in the local environment using ckanext-unhcr `master` branch (there's something weird with SSO on `external-data-deposit`, but it's a separate issue)

I'd like to try the following fix in UAT:
1. https://github.com/okfn/docker-ckan-unhcr-aws/pull/21
2. https://github.com/okfn/ckanext-saml2/pull/2

Can you review them? If happy we can tag a new version of ckanext-saml2 and update the Dockerfile
