### ISSUE TITLE
Need for more informative error messages

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#437]
![screenshot-3672b415](https://user-images.githubusercontent.com/3184712/99082805-ef16d200-25c4-11eb-9a07-0ca8a2a93a91.jpg)

Error occurred when saving a resource, please let me know if you would like me to get more details from the user.

**Comment by chris48s** [comment]
going to close this one as we've now switched to a different storage plugin with different error handling behaviour
