### ISSUE TITLE
Fix API file uploads

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#448]
Creating a resource with a large file upload via the API succeeds, but the resource gets marked as deleted. Small file uploads are fine.
I think this is a complete explanation of what's going on here.

- When we call `resource_create`, CKAN calls `package_update` with `defer_commit: True`: https://github.com/ckan/ckan/blob/c04b6d64aadc7a647b8896279002626ca3be0a56/ckan/logic/action/create.py#L314-L316
- `package_update` kicks off the package `after_update` job, even though we haven't persisted the package yet: https://github.com/ckan/ckan/blob/c04b6d64aadc7a647b8896279002626ca3be0a56/ckan/logic/action/update.py#L331-L334
- Our package `after_update` job is now running
- Meanwhile back in `resource_create` we block on this statement for ~10 seconds or something while we persist a large file to Amazon S3 https://github.com/ckan/ckan/blob/c04b6d64aadc7a647b8896279002626ca3be0a56/ckan/logic/action/create.py#L326-L327
- Before we've finished that, our package `after_update` job has called `package_show` on the package we haven't committed yet https://github.com/okfn/ckanext-unhcr/blob/4225819138e17236388933068ad7b8400197bbb7/ckanext/unhcr/jobs.py#L62 and `package_update` to save it back to the DB https://github.com/okfn/ckanext-unhcr/blob/4225819138e17236388933068ad7b8400197bbb7/ckanext/unhcr/jobs.py#L69
- The `package_update` action is called with a resources list that doesn't include the resource we're in the process of creating. Deep in the innards of CKAN, it picks up the inconsistency and sets it to deleted for us here https://github.com/ckan/ckan/blob/c04b6d64aadc7a647b8896279002626ca3be0a56/ckan/lib/dictization/model_save.py#L97-L100
- Meanwhile back in `resource_create` we have now finished saving the resource so we commit the transaction https://github.com/ckan/ckan/blob/c04b6d64aadc7a647b8896279002626ca3be0a56/ckan/logic/action/create.py#L329
- `package_create` then returns the package dict without calling `model.Session.refresh()`. Hence the state being 'active' in the API response despite the fact we already set it to 'deleted'

So.. lots of fun times there. I think there's a few different things we could consider doing here of varying levels of complexity and robustness:

- Don't run background jobs if `context['defer_commit'] == True`. Seems like this is always a recipe for race conditions and inconsistent DB content. The downside is any time we use `defer_commit` (sometimes this is a choice made for us in core) we won't ever populate the fields we're calculating in the background job.
- When we call `package_update`, call it with a blank resource list and `allow_partial_update=True`. That should stop us from marking resources as deleted if they haven't been committed yet, but it does mean that when resources are uploaded via the API the data_range and weight fields will have been calculated without including the most recently uploaded resource (because we'll still be calling `package_show` before we've commited).
- Pass the `defer_commit` flag to the background job. Calling `package_update` with `defer_commit` in https://github.com/okfn/ckanext-unhcr/blob/4225819138e17236388933068ad7b8400197bbb7/ckanext/unhcr/jobs.py#L68 might work (although I'm not sure if the background job will share the session). Even if it does we will have the same issue that the data_range and weight fields will have been calculated without including the most recently uploaded resource (because we still call `package_show` before we've commited).
- I think the reason this doesn't happen when we upload via the front-end is because the last thing we do in `finish_multipart` is call `package_patch`. We could just make `resource_create` a chained action that does all its gubbins and then calls `resource_update` at the end to set `state='active'`. `resource_update` has all the same problems, but because that last call to `resource_update` only touches the metadata it doesn't need to sit there waiting on IO with s3 so https://github.com/okfn/ckanext-unhcr/blob/4225819138e17236388933068ad7b8400197bbb7/ckanext/unhcr/jobs.py#L16 covers us long enough to get everything persisted before we call `package_show`. Then we will set the resource to deleted but then set it to active again at the end and re-generate the calculated fields off the full resource list. As long as jobs execute in order rather than asynchronously we should end up in the right state at the end. This is probably the most hacky solution but probably will eventually leave us with correct data (as long as the jobs execute in order) and I think this is what is actually happening when we upload via the web UI.
- It seems like it should be possible to try and work out if the transaction is still in progress and wait until it is finished before we kick off the job (with some timeout to prevent an infinite loop). I did have a go at trying to work this out when we call `after_update`, but `context['session'].dirty` returns `IdentitySet([])`. Am I looking at the wrong thing here? If I can work this out, it seems like this would be the most robust approach.

In general, it feels like buggy behaviour in CKAN that it kicks off background jobs when defer_commit is True before the commit happens. This could be particularly bad if we never commit and roll back the transaction after the job has started, but given the commit may occur outside `package_update` I guess it is hard to be sure they are being kicked off in the correct place.

**Comment by amercader** [comment]
You are right, the the fact that the `after_update` and `after_create` hooks are called before the actual commit is not ideal and leads to really confusing scenarios.

I think the best course of action would be to not use this hooks at all and instead fire the background jobs when we are sure that the resource has been created and committed to the DB. I think the safest place to do that is a chained `package_update` action, once the core action has been called (so we are sure the update was committed)

**Comment by chris48s** [comment]
I'm slightly unclear on your suggestion. Are you saying
- we should still do this work in background jobs but change the point in the code where we kick off the jobs
or
- we should stop doing this work in background jobs and bring it onto the critical path

?

**Comment by amercader** [comment]
Sorry if I wasn't clear, I meant the first one:
> we should still do this work in background jobs but change the point in the code where we kick off the jobs

ie, call `toolkit.enqueue(jobs.process_data_fields_or_whatever_is_called, [dataset['id']])` in a chained `package_update` action
