### ISSUE TITLE
Request/Grant access to datasets

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#451]
There still seems to be some errors when people are requesting access to private data on RIDL. I will try to get more information on what they get as a server error message when she tries to submit a request.

Also, when user Lauren Herby tried to grant access to a dataset (this one https://ridl.unhcr.org/dataset/cmr-sea-covid-19-refugees-and-asylum-seekers-in-adamaoua-east-and-north-regions-may-2020), she got an error message. See screenshot of message below:
![image](https://user-images.githubusercontent.com/3184712/101369331-77c51d00-38a8-11eb-9003-b680a265c2df.png)

**Comment by chris48s** [comment]
One of the things we need to to to fix this will be to upgrade the Collaborators plugin once this is fixed https://github.com/okfn/ckanext-collaborators/pull/20
We're currently running 0.0.5. If I upgrade it to 0.0.8 we have a failing test so the upgrade will require us to make at least one change to account for it. I'm going to kick that can down the road slightly and deal with it when we've got a version with that fix applied to upgrade to.

Refs:
* https://github.com/okfn/ckanext-unhcr/blob/4028aed6e22f6b06b8f53cb4aa3c42e6bcbc018e/bin/install-extensions.bash#L12
* https://github.com/okfn/docker-ckan-unhcr-aws/blob/403087db156499abdfe7a1759884ab85cca340ec/ckan/Dockerfile#L25
* https://github.com/okfn/ckanext-collaborators/compare/0.0.5...0.0.8
* https://github.com/okfn/ckanext-unhcr/runs/1551522582
