### ISSUE TITLE
Organization / About doesn't display some fields

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#461]
Example: This container does have values set for "Parent" and "Visible to partner users"

![Screenshot_2020-12-16 Edit - Burundi - Data Containers - RIDL](https://user-images.githubusercontent.com/6025893/102348163-5f848a80-3f99-11eb-8b25-d2c8e7c0ef83.png)

but they aren't shown on the about page:

![Screenshot_2020-12-16 About - Burundi - Data Containers - RIDL](https://user-images.githubusercontent.com/6025893/102348175-67442f00-3f99-11eb-84fa-dd7d2a1bb43d.png)

**Comment by avdata99** [comment]
This is probably related: https://lists-archive.okfn.org/pipermail/ckan-dev/2016-March/021160.html
