### ISSUE TITLE
Add "Required field" notice in data container form

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#49]
Not sure why, but the "Required field" notice is missing in the data container form, this is the one on the dataset one:

![screenshot-2018-5-2 create dataset - ckan](https://user-images.githubusercontent.com/200230/39520288-5c18f30a-4e0a-11e8-93f1-ede64665d6b4.png)

**Comment by roll** [comment]
@amercader 
I don't see ckan itself have it:
- https://github.com/ckan/ckan/blob/master/ckan/templates-bs2/organization/snippets/organization_form.html#L34
- https://github.com/ckan/ckan/blob/master/ckan/templates-bs2/package/snippets/package_form.html#L24

Should we add it manually?

**Comment by amercader** [comment]
Yes, please add it manually. This is a bug in CKAN core.

**Comment by amercader** [comment]
Found the issue on ckanext-scheming (ckan/ckanext-scheming#180). Using a local patch for now on our setup
