### ISSUE TITLE
Migrate API keys to tokens

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#537]
CKAN 2.9 introduces API tokens and we want to migrate all RIDL users from keys to tokens.

Once we are migrated to CKAN 2.9 we should:
- Contact all registered RIDL users telling them API keys will be removed on date X and they should migrate to tokens
- Add a banner in the frontend saying the same thing
- One date X we set everyone's API key to None and remove all the buttons that allow you to generate or set a key

**Comment by chris48s** [comment]
Research point: Who is currently using keys? Can we see request headers in the AWS CloudWatch logs?

**Comment by chris48s** [comment]
TODO: should tokens be passed in `Authorization` or `X-CKAN-API-Key` header?

**Comment by avdata99** [comment]
Closed with #1023
