### ISSUE TITLE
Patch releases

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#557]
https://github.com/ckan/ckan/releases/tag/ckan-2.8.8 and
https://github.com/ckan/ckan/releases/tag/ckan-2.9.3 exist

Once the docker images are updated,
- docker pull and run the tests for both current branches (master + 2.9) against the new images - does everything still work?
- make sure all the core patches still apply?
- are there any we don't need any more?

assuming its all fine, get a 2.8.8 build deployed on UAT

**Comment by chris48s** [comment]
Updating to the latest patch release does allow us to remove at least one core patch
https://github.com/okfn/docker-ckan-unhcr-aws/blob/master/ckan/patches/ckan/08_task_status_update.patch
review the rest of the changelogs
https://docs.ckan.org/en/2.8/changelog.html#v-2-8-8-2021-05-19
https://docs.ckan.org/en/2.9/changelog.html#v-2-9-3-2021-05-19

**Comment by amercader** [comment]
`okfn/ckan-base` and `okfn/ckan-dev` images are now updated to 2.9.3
