### ISSUE TITLE
CKAN 2.9: Resolve remaining test failures

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#564]
You have still got a small number of test failures outstanding on the CKAN 2.9 branch. Review these and fix the bugs/update the tests as applicable. Getting the build green will give us more confidence and make development/review easier as we work through the rest of the migration tasks.

**Comment by chris48s** [comment]
I think the only thing left that isn't covered by an open PR is the
`IndexError: list index out of range` fail
on `test_both_types_data_fields_missing`
in `test_schema.py`

**Comment by chris48s** [comment]
The final test failure is down to an issue in core.
Reverting this commit https://github.com/ckan/ckan/commit/7b6702b6c17efbe0b2b7eb46ab46da86e387c55c takes us back to the CKAN 2.8 behaviour, which gets the test to pass
@amercader to pick up..

**Comment by chris48s** [comment]
refs https://github.com/ckan/ckan/pull/6119
For now I'm going to mark it skipped
When you circle back to this, also replace `'url': 'http://example.com/data.csv'` with a `FakeFileStorage`

**Comment by amercader** [comment]
I've created https://github.com/okfn/docker-ckan-unhcr-aws/pull/40 which contains the patch I submitted to CKAN core addressing this https://github.com/ckan/ckan/pull/6149
