### ISSUE TITLE
Request Data Container does not work

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#609]
## To Reproduce the Error

- Log in as a non-sysadmin user (who is admin of at least one container)
- Fill in the "Request Data Container" form
- Submit the form
- You'll get directed to a "404 Not Found: Group not found" page
- No record will be inserted, no request will be visible on dashboard

## Desired Behaviour 

What should happen is a "pending" data container should be created, the requesting user should see a page like this:
![Screenshot at 2021-06-15 13-33-18](https://user-images.githubusercontent.com/6025893/122053725-e8f90600-cdde-11eb-9112-35e7e2083850.png)
and if you log in as a sysadmin, you should have a request which you can approve or reject
![Screenshot at 2021-06-15 13-35-14](https://user-images.githubusercontent.com/6025893/122053842-03cb7a80-cddf-11eb-820f-efde4325d96b.png)
both of which should work.

**Comment by chris48s** [comment]
Hmm.. so this actually works fine if you are an admin of the parent container you are trying to create underneath. It only fails if your role is "member". So maybe the bug is really that unprivileged users should only be able to request a new container under a container they are an admin of, not one they are just a member of?
I am now unsure what the original business requirement was here :confused: probably need to confirm it with client or do some archaeology

**Comment by chris48s** [comment]
@avdata99  I dug out the original PR for this the other day and I think the solution is that on the "request container" form, only containers where the user's role is admin should be shown as possibilities for the parent container. If they are only member, those should be hidden from the list. That should solve it.

**Comment by chris48s** [comment]
for reference the original PR was https://github.com/okfn/ckanext-unhcr/pull/29

**Comment by avdata99** [comment]
Notes:

We changed the main function to define allowed parents

```python
def get_allowable_parent_groups(group_id):
    deposit = get_data_deposit()
    groups = hierarchy_helpers.get_allowable_parent_groups(group_id)
    groups = filter(lambda group: group.name != deposit.get('name'), groups)
    return groups
```

Original from `ckanext-hierarchy`

```python
def get_allowable_parent_groups(group_id):
    if group_id:
        group = model.Group.get(group_id)
        allowable_parent_groups = \
            group.groups_allowed_to_be_its_parent(type='organization')
    else:
        allowable_parent_groups = model.Group.all(
            group_type='organization')
    return allowable_parent_groups
```
