### ISSUE TITLE
Allow user to tag datasets with geographic metadata

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#619]
Once we have completed #618 we will also need the ability to tag datasets with geographies.
The specifics of this part of the job are currently less clear in my mind, but I'm zeroing in on them as I think about it..

Some requirements and assumptions we are already clear on:

- Geographic tags apply to datasets not resources
- Relationship is one-to-many: One dataset can be tagged with many geographies (including at the same level. One dataset can be apply to multiple countries, for example)
- Geography is not constrained by data container. Any dataset can be tagged with any geography. It is up to humans to make good decisions
- At any given time the user can tag datasets with whatever geographies are 'current' at the point of upload but as time passes we will end up with datasets that are associated with geographies which are no longer current
  **TODO**: more notes on how we deal with versioning/change over time TBC
- Datasets are related to units of geography by `pcode`

Probably the hard part of this is the interface we give users to pick geographies with. These lists have lots of things in them:

- Countries: ~200
- Populations of Concern: ~13,000
- Admin 1: ~3,000
- Admin 2: ~30,000
- Reference places: ~200,000

How do we allow users to meaningfully pick from a list of >10,000 possible options?

I think in the first instance there are a few techniques we could use to create a serviceable solution. A good solution probably uses several things from this list, but maybe not all of them...

1. Text search: Searching for places by name can help us but it is not a complete solution. Place names are often ambiguous. https://en.wikipedia.org/wiki/List_of_popular_place_names
2. Hierarchy: UN pcodes are hierarchical. For example, the code for admin2 area Nadirshahkot is `20AFG026004`. The AFG part tells us it is in Afghanistan and the `026` part tells us this admin2 area is inside admin1 area `20AFG026`. See the diagram in #618 . This means if we know some higher levels of goegraphy we can constrain our full text search by the higher level areas. For example the search query `name LIKE '%nadir%'` might match lots of admin2 areas globally but if we know the dataset is tagged with `AFG` for Afghanistan and `PAK` for Pakistan, we could also constrain that search to `AND (pcode LIKE '%AFG%' OR pcode LIKE '%PAK%')` to narrow things down.
3. Additional data: We can use the hierarchy or additional fields from the API responses to show the user more than just the name we're searching for. For example, if I'm searching for an admin area that has multiple matches, showing the list
    - San Jose
    - San Jose
    - San Jose
    - San Jose
    - ...
      is not helpful, but if we presented this as:
    - San Jose, Argentina (20ARG010063)
    - San Jose, Belize (20BLZ004001)
    - San Jose, Colombia (20COL017665)
    - San Jose, Nicaragua (20NIC010012)
    - ...
    then this list becomes more useful. Maybe we can do some of this work of attaching information from up the hierarchy at import time to make querying faster?
4. Allow the user to search/tag directly by pcode. "San Jose" is ambiguous. `20NIC010012` is clear.

Between those things we can probably arrive at a workable interface.

One thing we will definitely need is an autocomplete API endpoint that can query our geography table(s) by
- partial name string
- partial pcode string
- geography type

which returns lists of names (including useful data from up the hierarchy).

Some questions I am still unclear on:

- Data model: How do we store the relationship between package and geography? Is it a link table like `package_tag` or is it a serialized object/list in `package_extras`?
- Should we require areas to be tagged with higher levels of geography in order to search lower areas or should we allow lower areas to be tagged independently and just search globally? How strict or loose should the hierarchy be?
- Is "geography tags" one concept, or are "countries", "populations of concern", "admin areas" etc all separate "fields" on a dataset?
- How do we do this in a CKAN friendly way? Can all this be done with a custom Scheming `form_snippet`? Is there anything I've laid out here that would be hard to do this way?

**Comment by amercader** [comment]
This has been implemented
