### ISSUE TITLE
Allow users to search datasets by geography

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#638]
This is a big meaty question which is currently somewhat poorly defined, but once we've implemented #619 there will be some requirement to search/discover datasets based on the geographies they are tagged with.

Some kind of text/hierarchy based discovery is likely to be a requirement. What is a good user-interface to this? Faceting will not work given there are >200,000 possible options.

Some kind of "search by bbox" might be a requirement at some point. Currently we are not storing geometries on the geography model. https://github.com/okfn/ckanext-unhcr/blob/72a541c828975505d362a3194d0592fee3f3fed9/ckanext/unhcr/models.py#L100 I think in order to do this we do need to store the geographies locally. IMO querying their ArCGIS API on the fly will not be performant enough. This will definitely increase the DB size and compute requirements for the RDS instance.

Reference Places and Populations of concern are just a point, so those aren't too hard to deal with.
Admin1/Admin2 and Country are (multi-)polygons. Countries are available as both 1m (full) precision and 15m (simplified) precision but even the simplified ones are quite big with a lot of points. Admin1/Admin2 are only available at full prevision.

**Comment by amercader** [comment]
See #767
