### ISSUE TITLE
Dataset metadata field, tooltip format is very different from others.

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#646]
![Selection_288](https://user-images.githubusercontent.com/3237309/127521943-35ed7fab-289b-4178-bf4e-9b75489b7929.png)

Environment: UAT - RIDL v3.1.1
Ref: [document](https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Funhcr365.sharepoint.com~2Fteams~2Fder-despcp-RIDLDevelopment~2FShared%20Documents~2FRIDL%20Development~2FFeedback~2FJuly2021_test_feedback.docx?threadId=19:dc78b97e5d144cf8a8018921a4a2e849@thread.tacv2&messageId=1627572583260&baseUrl=https:~2F~2Funhcr365.sharepoint.com~2Fteams~2Fder-despcp-RIDLDevelopment&fileId=84D3DB77-B63F-4199-91DA-1570AF7A9F03&ctx=chiclet&viewerAction=view)

**Comment by chris48s** [comment]
I actually fixed this the other day in https://github.com/okfn/ckanext-unhcr/pull/639 :)

**Comment by avdata99** [comment]
Fixed with #639

![Selection_307](https://user-images.githubusercontent.com/3237309/127876189-c805e04c-4d2a-42e5-93d2-84b35f53c1c7.png)
