### ISSUE TITLE
[Meta] Support DDI datasets

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#65]
This is a meta issue, there are other issues created for specific tasks.

## Context

From http://www.ddialliance.org:

> The Data Documentation Initiative (DDI) is an international standard for describing the data produced by surveys and other observational methods in the social, behavioral, economic, and health sciences.

DDI codebooks contain metadata for a particular dataset and can be generated in human-friendly (PDF) or machine-friendly (XML) formats. Here are some examples of XML codebooks:

https://www.icpsr.umich.edu/icpsrweb/ICPSR/ddi25/studies/4245 
https://www.ddialliance.org/sites/default/files/NHS-99M001X-E-2011-pumf-individuals.xml 

## Goals

1. Support ingestion of DDI datasets into RIDL:
  a. Publishers should be able to provide a DDI XML file, a DDI RDF file and associated data or attachment files
  b. Metadata from the DDI XML file should be validated using the same schema that other RIDL datasets use
  c. DDI datasets should be able to be displayed and queried in the same way as other datasets
2. Support consumption of DDI datasets from RIDL via the created resources:
  a. For the first stage we will consider than exposing all DDI files (XML, RDF and data files) as part of a dataset in RIDL fulfills this requirement.
b. If at a later stage the actual requirements for consuming DDI datasets from RIDl are clearer we will reassess and estimate potential modifications needed 

## Proposed implementation

We’ll build on top of ckanext-ddi. It provides various things, but for our own needs the most important ones are:

* A parser that can read DDI files and extract specific fields, creating a CKAN dataset
* A custom form for uploading DDI files

This will be used to implement a custom workflow for uploading DDI files, in parallel to normal RIDL datasets.

![68747470733a2f2f7261772e6769746875622e636f6d2f6c6969702f636b616e6578742d6464692f6d61737465722f73637265656e73686f74732f6164645f646174617365745f627574746f6e2e706e67](https://user-images.githubusercontent.com/200230/40837792-f3ea5540-659b-11e8-8dae-f8698f3bc3af.png)

The current implementation in ckanext-ddi only allows to upload the XML metadata file, but in RIDL we need to support also the uploading of a companion RDF file and of the actual data files. This will mean:

* Modifying the controller to allow upload of a companion DDI RDF file
* Once the metadata from the XML file is extracted and validated against the RIDL schema, continue to the resources section of the dataset form to upload the data files
* (CONFIRM) Modify the DDI RDF so the resource URL / path points to the one hosted in RIDL. TODO: find out the XPath of the property to modify on the RDF file.

To simplify things it has been agreed that DDI datasets should have the same metadata schema than the rest of RIDL fields. So when uploading an XML file and extracting the field values, if a mandatory field is missing or a list does not contain one of the pre-defined values, users should get a validation error and the dataset should not be created.

PENDING: To be able to map the fields in the DDI XML file to the CKAN/RIDL fields we need to know the XPath (ie where in the XML) for all properties that map to RIDL fields. For instance for the field `geographic_coverage` the XPath used to extract the value in the XML is `//ddi:codeBook/ddi:stdyDscr/ddi:stdyInfo/ddi:sumDscr/ddi:geogCover`.

The following spreadsheet can be used to map RIDL fields to DDI and provide the necessary XPath:

https://docs.google.com/spreadsheets/d/1qyLLIhvyoeNHkhny-B_bV2LY58nw7bidbd27oWoNWcM/edit#gid=0

**Comment by roll** [comment]
https://github.com/okfn/ckanext-ddi
