### ISSUE TITLE
Compatibility with 2.8?

### ISSUE THREAD

**Issue by mystycs** [okfn/ckanext-unhcr#71]
I tried running this on 2.8 but i get internal server error when starting ckan.

Please see error below:

Anyone have any suggestions or have faced this issue or know of the fix?

Looks like some controller issue with flask?

> ckan          | [2018-06-27 14:29:15,124] ERROR in app: Exception on / [GET]
> ckan          | Traceback (most recent call last):
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
> ckan          |     response = self.full_dispatch_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
> ckan          |     rv = self.handle_user_exception(e)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
> ckan          |     return self.handle_http_exception(e)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
> ckan          |     return handler(e)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 412, in error_handler
> ckan          |     return base.render(u'error_document_template.html', extra_vars), e.code
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/base.py", line 127, in render
> ckan          |     return flask_render_template(template_name, **extra_vars)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
> ckan          |     context, ctx.app)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
> ckan          |     rv = template.render(context)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
> ckan          |     return self.environment.handle_exception(exc_info, True)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
> ckan          |     reraise(exc_type, exc_value, tb)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/templates/error_document_template.html", line 1, in top-level template code
> ckan          |     {% extends "page.html" %}
> ckan          |   File "/usr/lib/ckan/venv/src/ckanext-unhcr/ckanext/unhcr/templates/page.html", line 1, in top-level template code
> ckan          |     {% ckan_extends %}
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/templates/page.html", line 1, in top-level template code
> ckan          |     {% extends "base.html" %}
> ckan          |   File "/usr/lib/ckan/venv/src/ckanext-unhcr/ckanext/unhcr/templates/base.html", line 1, in top-level template code
> ckan          |     {% ckan_extends %}
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/templates/base.html", line 101, in top-level template code
> ckan          |     {%- block page %}{% endblock -%}
> ckan          |   File "/usr/lib/ckan/venv/src/ckanext-unhcr/ckanext/unhcr/templates/page.html", line 5, in block "page"
> ckan          |     {% if h.page_authorized() %}
> ckan          |   File "/usr/lib/ckan/venv/src/ckanext-unhcr/ckanext/unhcr/helpers.py", line 44, in page_authorized
> ckan          |     if (toolkit.c.controller == 'error' and
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
> ckan          |     return getattr(self._get_current_object(), name)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
> ckan          |     return getattr(self._get_current_object(), name)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 334, in __getattr__
> ckan          |     return getattr(app_globals.app_globals, name)
> ckan          | AttributeError: '_Globals' object has no attribute 'controller'
> ckan          | Traceback (most recent call last):
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
> ckan          |     self.finish_request(request, client_address)
> ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
> ckan          |     self.RequestHandlerClass(request, client_address, self)
> ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
> ckan          |     self.handle()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
> ckan          |     BaseHTTPRequestHandler.handle(self)
> ckan          |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
> ckan          |     self.handle_one_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
> ckan          |     self.wsgi_execute()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
> ckan          |     self.wsgi_start_response)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
> ckan          |     return self.apps[app_name](environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
> ckan          |     app_iter = app(environ, wrapper.wrap_start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
> ckan          |     resp = self.call_func(req, *args, **self.kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
> ckan          |     return self.func(req, *args, **kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
> ckan          |     return request.get_response(self.app)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
> ckan          |     application, catch_exc_info=False)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
> ckan          |     app_iter = application(self.environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
> ckan          |     resp = self.call_func(req, *args, **self.kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
> ckan          |     return self.func(req, *args, **kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
> ckan          |     response = request.get_response(self.app)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
> ckan          |     application, catch_exc_info=False)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
> ckan          |     app_iter = application(self.environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
> ckan          |     return self.wsgi_app(environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
> ckan          |     return self.wrap_app(environ, session_start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
> ckan          |     response = self.handle_exception(e)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1547, in handle_exception
> ckan          |     return self.finalize_request(handler(e), from_error_handler=True)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 411, in error_handler
> ckan          |     extra_vars = {u'code': e.code, u'content': e.description}
> ckan          | AttributeError: 'exceptions.AttributeError' object has no attribute 'code'

**Comment by amercader** [comment]
This particular issue should be fixed by https://github.com/ckan/ckan/pull/4257, that needs to be backported, but you will likely get more issues if trying to use the extension. This extension is heavily customized for a particular instance and relies on other extensions, so I suggest you extract the bits you are interested in rather than trying to use it as a whole.

**Comment by mystycs** [comment]
I ended up going to 2.7.x

**Comment by mystycs** [comment]
Also what is the main purpose of this extension?
