### ISSUE TITLE
Error to approve deposit dataset

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#710]
To reproduce
 - Request access for an external user
 - Approve the user
 - External user creates a deposit dataset
 - Admin try to approve this dataset

![image](https://user-images.githubusercontent.com/3237309/135658734-2cd619c9-09e4-4a9c-af4d-14783c4fd099.png)

**Comment by avdata99** [comment]
Probably [this change](https://github.com/okfn/ckanext-unhcr/commit/d167370a92bd67c75dc4ae79231495ddf8ce98e0) breaks something

**Comment by avdata99** [comment]
The `type` field for packages [is inmutable](https://github.com/ckan/ckan/blob/ckan-2.9.4/ckan/logic/action/update.py#L259-L261)
But [we change](https://github.com/okfn/ckanext-unhcr/blob/release-3.1.4b/ckanext/unhcr/helpers.py#L735) from `deposited-dataset` to `dataset`when [we approve a dataset](https://github.com/okfn/ckanext-unhcr/blob/release-3.1.4b/ckanext/unhcr/blueprints/deposited_dataset.py#L46).

We are validating a `dataset` as if it were a `deposited-dataset`

**Comment by amercader** [comment]
@avdata99 I could not reproduce this locally (I could not try in UAT because of #713 )

Core doesn't allow switching types but we do applying [this patch](https://github.com/okfn/docker-ckan-unhcr-aws/blob/master/ckan/patches/ckan/03_package_update_type_change.patch). Are you sure you are applying it locally?

**Comment by avdata99** [comment]
@amercader, Yes, I have the patch. I sometimes override CKAN core source code in the docker volume to debug and that's the problem here.
