### ISSUE TITLE
Discover: Improve geog_coverage field

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#735]
The `geog_coverage` field will probably be no longer useful once we implement the `geographies` field

Analyze how we currently use this field and if it's possible to replace/remove it.

**Comment by avdata99** [comment]
`geog_coverage` usage in production:

<pre>
                 geog_coverage                     | total
---------------------------------------------------+-------
EMPTY                                              |   226
National coverage                                  |    25
National                                           |    22
Regional, Americas                                 |    11
National & 11 departments (Admin 1)                |     5
XXXX                  Refugee Camps                |     4
AXXXez                                             |     4
Global                                             |     3
Latin America Caribbean                            |     3
Urban areas at National Coverage                   |     3
16 UNHCR managed sites in XXXX                     |     3
.... (and much more)
</pre>

Query:

```sql
SELECT left(value, 50) as geog_coverage, count(*) as total
 FROM public.package_extra
 where package_extra.key = 'geog_coverage'
 group by package_extra.value
 order by total desc;
```

This field is used as a free text. We can move it into dataset notes (something like Geographic coverage: XXXX) and delete the field.
With the new Geographies field, we can determine the coverage level for each used Geography (Country, Admin 1, Admin 2, etc)

**Comment by avdata99** [comment]
A better way to see them: /api/action/package_search?q=*:*&facet=on&facet.field=[%22geog_coverage%22]&rows=0

**Comment by avdata99** [comment]
Some usage examples
 - `National` and `National coverage`: Used 43 times for different countries.
 - `National & 11 departments (Admin 1)` is used 3 times for Colombia

In most cases, you need to read the titles and description of the dataset to connect to the corresponding geographies.
The shortest path to achieve this is to go one by one updating geographies and after that, remove the `geog_coverage` field

@amercader do you think we must create some UI tool to improve this process or propose to change this manually?

About DDI references for geog_coverage, #750 was created

**Comment by amercader** [comment]
> @amercader do you think we must create some UI tool to improve this process or propose to change this manually?

No, definitely not create a UI for this. It can be done manually with a cup of coffee, tea or mate. I think the UNHCR team can take care of this.

**Comment by avdata99** [comment]
Move this field to the description and show a note near new `geographies` field to show users we have some information

**Comment by avdata99** [comment]
We will continue using this field so far because DDI use it.
