### ISSUE TITLE
Allow users to search datasets by geography in a map

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#767]
Provide a map widget where users can draw an area of interest. It requires that we index the geometry (or an approximation of it) of all the geographies we are currently storing, which means changes at the DB and Solr level.

This will require to:
 - [ ] Start saving the geometries in the database
 - [ ] Allow bounding box search
 - [ ] Show a map in the UI to search

Analyze:
 - ckanext-spatial: https://github.com/ckan/ckanext-spatial
 - USA/GSA [location search](https://github.com/GSA/ckanext-geodatagov/blob/0853bee402148f7ccabc8f37ca8c10088e6dcb42/ckanext/geodatagov/logic.py#L23)

**Comment by amercader** [comment]
Some previous notes from Chris in #638:

---

This is a big meaty question which is currently somewhat poorly defined, but once we've implemented #619 there will be some requirement to search/discover datasets based on the geographies they are tagged with.

Some kind of text/hierarchy based discovery is likely to be a requirement. What is a good user-interface to this? Faceting will not work given there are >200,000 possible options.

Some kind of "search by bbox" might be a requirement at some point. Currently we are not storing geometries on the geography model. https://github.com/okfn/ckanext-unhcr/blob/72a541c828975505d362a3194d0592fee3f3fed9/ckanext/unhcr/models.py#L100 I think in order to do this we do need to store the geographies locally. IMO querying their ArCGIS API on the fly will not be performant enough. This will definitely increase the DB size and compute requirements for the RDS instance.

Reference Places and Populations of concern are just a point, so those aren't too hard to deal with.
Admin1/Admin2 and Country are (multi-)polygons. Countries are available as both 1m (full) precision and 15m (simplified) precision but even the simplified ones are quite big with a lot of points. Admin1/Admin2 are only available at full prevision.

**Comment by amercader** [comment]
Some random thoughts about this.

First of all, spatial searches are *hard*. It's tempting to jump to an implementation and start building things and then you are hit with performance or storage issues so let's plan this properly.

At a higher level, a spatial search works in the following way:
1. Your searched items (datasets in our cases) need to have a geometry or geometries associated. These are generally points, bounding boxes (a rectangle covering the extent of the thing) or a polygon with the actual geometry (which can be simplified at different levels)
2. These geometries are spatially indexed in a spatially-enabled search engine
3. When a search is performed, the user provides an input geometry, and a spatial operation is performed. The most common case is probably the user providing a bounding box, and the search engine checks if that intersects with any of the indexed geometries. Other options can include for instance providing a point and returning geometries within a certain distance of that point.

In CKAN terms, when using ckanext-spatial this has meant traditionally:
1. Store a GeoJSON version of the geometry as an extra called `spatial` in a dataset
2. Depending on the [backend](http://docs.ckan.org/projects/ckanext-spatial/en/latest/spatial-search.html#choosing-a-backend-for-the-spatial-search) you choose, a different version of this gets stored. When using `postgis` or `solr-spatial-field`, the whole geometry gets stored, when using `solr`, just the bounding box
3. A [map widget](http://docs.ckan.org/projects/ckanext-spatial/en/latest/spatial-search.html#spatial-search-widget) is added to the dataset search page, the drawn bbox is passed to the `before_search()` hook, where depending on the backend the relevant Solr query params are computed, or the Postgis query is performed.

The Postgis backend has severe limitations as it basically first performs the spatial search in Postgis and then filters the Solr results with the datasets filtered, so I'd discard it to implement this. In fact, it has long been an aim of mine to[ *not* require Postgis](https://github.com/ckan/ckanext-spatial/issues/195) to install ckanext-spatial as it is difficult to deploy. So maybe we'll take this opportunity to refactor the extension. Given that some geographies have polygon geometries (countries and admin1/2) I'd perhaps explore the `solr-spatial-field` option.

I haven't used this in a very long time so we would need to investigate what changes are [needed in Solr 8](https://solr.apache.org/guide/8_11/spatial-search.html) as the ones described in the current docs are almost surely outdated 

Other thoughts:

* Storing the full resolution geometries for all countries and admin1/2 geographies may not be needed. Maybe we can simplify them when storing them

Next steps:

* Let's make sure ckanext-spatial currently works as expected. Try to set up the spatial search locally with CKAN 2.9 and Solr 8 using the `solr` and `solr-spatial-field` backends and make sure that everything works as intended. Although the tests pass in CKAN 2.9 and 2.10 we should try that the widgets work as intended.
* In parallel I'll try to make the Postgis requirement optional to simplify our life (and everyone's)

**Comment by avdata99** [comment]
Testing `ckanext-spatial` on ckan 2.9

![image](https://user-images.githubusercontent.com/3237309/183664710-5ca92162-8dc3-4797-b8eb-0501e4669fb5.png)

![image](https://user-images.githubusercontent.com/3237309/183664779-ccf9196f-e4d0-4cb2-b221-cafd5f05544d.png)

![image](https://user-images.githubusercontent.com/3237309/183664633-e512edf4-c50d-4001-81c7-f5919425c781.png)

![image](https://user-images.githubusercontent.com/3237309/183664572-bea6de81-d504-4e03-adf7-ceda8abc2e3a.png)

**Comment by avdata99** [comment]
Working PRs
 - docker https://github.com/okfn/docker-ckan-unhcr-aws/pull/88
 - unhcr https://github.com/okfn/ckanext-unhcr/pull/862

**Comment by amercader** [comment]
@avdata99 I think we are ready to test the new v2 version of ckanext-spatial with some real live RIDL examples. Here's roughly how I would approach it:

1. Set things up, we need:
     1. ckanext-spatial running on the `dev-v2.0` branch installed. Set the `ckanext.spatial.search_backend=solr-spatial-field` config option
     2. Solr running with the spatial fields. You can use the `ckan/ckan-solr:2.9-solr8-spatial` image for now
     3. PostGIS installed and a new geometry field in our geographies table 
2. Store some geometries, which I think is done
3. Index these geometries. We need to use a custom indexing logic, as described [in the new documentation](https://docs.ckan.org/projects/ckanext-spatial/en/dev-v2.0/spatial-search.html#custom-indexing-logic). In our case, as we are using the spatial field option we basically need some custom logic in ckanext-unhcr's `before_dataset_index()` method. In here we need the [WKT](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry) version of the geometries linked to the all locations associated with a dataset, and assign a list of those to the `dataset_dict["spatial_geom"]` field. So something like:
    ```python
    pcodes = dataset_dict.get("geographies")

    # We can use PostGIS' ST_AsEWKT() function to get the geometries in the right format
    # https://postgis.net/docs/ST_AsEWKT.html
    # The syntax below is probably wrong but you get the idea
    results = model.Session.execute("SELECT ST_AsEWKT(the_geom) AS wkt FROM geographies WHERE pcode in (:pcodes)", {"pcodes": pcodes})

    dataset_dict["spatial_geom"] = [r["wkt"] for r in results]

    ```
4. Rebuild the index and test it! API is probably easier first, https://localhost:5000/api/action/package_search?ext_bbox={minx},{miny},{maxx},{maxy}
5. If the API looks fine, include the [spatial search widget](https://docs.ckan.org/projects/ckanext-spatial/en/dev-v2.0/spatial-search.html#spatial-search-widget) so it's easier to test and combine with other searches.

Thinks to look out for:
* Size of the indexed geometries. I'm almost certain that we will need to heavily simplify countries and admin areas, or even just use the bounding box if they are bigger than a certain size (or rather they have a count of nodes > X). All this processing can be done in Postgis. Initially we can make it on the fly on each `before_index()` call, but if it proves to be slow we can pre-process all geometries as part of a background job
* Ordering of results, I'm really interested in this as we may need to tweak the Solr queries to get results ordered properly from a spatial point of view. Or maybe we want to boost smaller units (populations of concern, and the other point based ones > admin > countries)

**Comment by avdata99** [comment]
TBD  @amercader 
Where are we now:

When we create or update a dataset we use the ´geographies´ field to create the ´spatial´ extra.
The ´geographies´ field is a list of ´pcodes´. Now, we have a ´Geography´ type field for each ´pcode´ in our internal ´Geography´ class.
We get the GeoJSON representation of this ´Geography´ to fill the ´spatial´ extra using always a `GeometryCollection` because we want to allow multiple geometries for each dataset.

This give us an error in the ´ckanext-spatial´' ´before_dataset_index´ method so I'm [proposing an update to spatial](https://github.com/ckan/ckanext-spatial/pull/293) to allow multiple Geometries.

Also, the ´spatial_geom´ is successfully built in the ´ckanext-unhcr´' ´before_dataset_index´ [method](https://github.com/okfn/ckanext-unhcr/blob/add_spatial_extension/ckanext/unhcr/plugin.py#L395) and work fine.
Maybe we don't need it and we should rely on spatial for this.

Note: we are not using the ´package_extent´ table. It looks that we don't need it.
