### ISSUE TITLE
Completely hide the data deposit organization

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-unhcr#78]
# Overview

We're going to have a separate UI section for data curation so we don't need to use the `/data-container/data-deposit` endpoint.

So we need completely forbid view access to everything related to the data deposit container (using datasets from it in the separate curating UI independently):
- list
- view
- streams
- api
- etc (review)

It seems by default ckan doesn't support private organizations:
https://stackoverflow.com/questions/24203875/hiding-organizations-in-general-list

We need to patch a few auth functions e.g. changing only `organization_show` is not enough because it breaks listing.

**Comment by amercader** [comment]
I think the easiest way to go is to create a new organization type / schema (`data-deposit`). This will give us a lot for free:

* Hide it from the default data container listing (ie tree)
* Dedicated endpoint (`/data-deposit`)
* No need to add required fields like country

If we get the dataset permissions right on #76 then I don't think we need much more custom auth than that. It's not a big deal if users can call `organization_show` on the data deposit, as long as they can not see what datasets are in there.

**Comment by roll** [comment]
@amercader 
At the moment you can see datasets information in the `data-deposit` activity stream. Even if you (an user) don't see any datasets. Is it a mistake in #76 or still something to take care separately?

**Comment by amercader** [comment]
No, we will need to restrict access to that activity stream as part of this issue.

**Comment by roll** [comment]
Now we use this org as a curation UI. So we don't need to hide it and I don't see want we need to restrict on top of current (dataset-level) restrictions.

Closing for now.
