### ISSUE TITLE
UI improvements for the curation process

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#81]
Overview of the Data Deposit and curation UI:

Issues prioritized in the milestone: https://github.com/okfn/ckanext-unhcr/milestone/1

* Data Deposit:  It is only accessible to sysadmins and curation team members. All deposited datasets are shown there, and there are filters for stage (draft, submitted, pending approval...) and for who is assigned to the datasets. (See #84).
* Custom deposited dataset page and form. (See #85 and #87).
* Tabs on the user dashboard (See #86)
   * For all users: My deposited datasets
   * For curator admins: Unassigned deposited datasets
   * For curator editors and admins: Deposited datasets assigned to me
* Curation activity stream (TBD)

**Comment by roll** [comment]
Admin and creator should be able to see basic details of assigned curator (name, email)

**Comment by amercader** [comment]
Keeping this here for reference:

If a curator approves a private dataset they will be redirected to a 404 page, as they don't have permissions to see private datasets that belong to another data container. After discussion with the client this is fine, we can sort it out at the app level for now, making editors sysadmins.

**Comment by roll** [comment]
All texts moved to https://github.com/okfn/ckanext-unhcr/issues/84
