### ISSUE TITLE
Datasets are listed incorrectly under some data containers

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#843]
Users found some issues on prod. Could you try this [link](https://ridl.unhcr.org/data-container/peru)? When I open it, I see 696 datasets listed as they belong to this container.  Same for other containers, such as Cameroon, etc.

**Comment by avdata99** [comment]
Internally, ´/data-container/peru´ Solr search gets 13 results

<pre>
params={
  q=*:*&
  facet.limit=50&
  df=text&
  fl=id+validated_data_dict&
  q.op=AND&
  fq=%2Bowner_org:"e3aa2f62-acd5-413a-8ce3-06960b739781"+%2Bstate:(active)&
  fq=%2Bsite_id:"ridl"&
  sort=score+desc,+metadata_modified+desc&
  facet.mincount=1&
  rows=0&facet=false&wt=json
} 

<b>hits=13</b> status=0 QTime=0
<pre>

 ... but shows 696

If we run a manual search, we get only those 13

![image](https://user-images.githubusercontent.com/3237309/175324200-89294231-7c24-4cae-9a3b-ee48eecb5416.png)

What am I not seeing @amercader ?

**Comment by avdata99** [comment]
Will #845 be enough @amercader?

**Comment by avdata99** [comment]
I validated the error and the fix locally.
It will be applied to UAT and the to production

**Comment by avdata99** [comment]
@mariannurban the hotfix was deployed to production and https://ridl.unhcr.org/data-container/peru shows what we expect
This was previously tested in UAT successfully. 
FYI: @amercader
