### ISSUE TITLE
Change GIS endpoit to get inactive geographies

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#850]
The current endpoint get only active geographies.
Start using a new one with ALL geographies and ensure all functionality remains the same.
Start importing Centroids (loc type 64)

**Comment by amercader** [comment]
Just to confirm, do we need to:

1. Import all geographies from the GIS server (active and inactive), store them in RIDL and allow users to select inactive geographies, or
2. If an existing geography in RIDL is inactivated in the GIS server, keep in RIDL as inactive and allow users to select it

I believe there is some existing logic for 2, If we need to go with 1 it would be good to check first how many new inactive geographies would be imported in case it's a huge number

**Comment by avdata99** [comment]
I sent an email past week with some question for the GIS team (you were copied)

About 1: 
We import layer by layer all geographies. One of the is for _Reference Places_ identified as `wrl_prp_p_unhcr_ALL`.  The new endpoint is called `wrl_prp_p_unhcr_ALL_with_INACTIVE` so I assume it only include _Reference Places_.
We don't allow inactive geographies to be selected. This is a new feature. Best choice will be to show all and label inactive ones.

About 2:
If a geography is inactive, we keep it inactive. This is done now..

I already run this #851. There are some more but it's not huge.
