### ISSUE TITLE
Deposited dataset form UI improvements

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#87]
- [x] Update the form's sidebar
- [x] We need a way to show Data Curators what fields are mandatory in a regular dataset while being in the deposited dataset form, so they don't have to go back an forth to the dataset read page. Using the red asterisks for required datasets would be confusing, as they can still save the datasets without filling these. One option is to use a special background for these fields that are required in a normal dataset, something like this (obviously looking better):
![screenshot_2019-02-28 datasets - ckan](https://user-images.githubusercontent.com/200230/53575239-70200280-3b71-11e9-8979-f8cef0ae3d54.png)
- [x] Data Depositors should not be thrown directly into the form. I think a previous page would be useful with an explanatory text describing the process, and where they would select the destination data container and the visibility setting. When they clicked a button they would be directed to the deposited dataset form. We'll need a custom endpoint and template for this, which is fine.
- [x] Can we show the actual validation errors for the resources on deposited datasets? Right now it just says "Resources invalid" without showing the missing fields.

estemate: 8h

**Comment by roll** [comment]
I'll check here if we can show resource validation errors. But actually I'm not sure that it's possible
