### ISSUE TITLE
PowerQuery using API endpoint to pull dataset metadata

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#871]
Hi @avdata99 ,

here's the query I'm using to populate the table I was showing during the meeting:

let
    Source = Json.Document(Web.Contents("https://ridl.unhcr.org/api/3/action/package_search?rows=1000", [Headers=[Authorization=""]])),
result = Source[result],
    results = result[results],
    #"Converted to Table" = Table.FromList(results, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"external_access_level", "unit_of_measurement", "license_title", "maintainer", "relationships_as_object", "geog_coverage", "private", "maintainer_email", "num_tags", "keywords", "admin_notes", "id", "metadata_created", "archived", "metadata_modified", "author", "author_email", "data_sensitivity", "state", "version", "data_collector", "creator_user_id", "type", "weight_notes", "resources", "data_collection_notes", "num_resources", "data_collection_technique", "tags", "clean_ops_notes", "visibility", "operational_purpose_of_data", "original_id", "groups", "license_id", "response_rate_notes", "relationships_as_subject", "organization", "name", "isopen", "sampling_procedure_notes", "url", "notes", "owner_org", "short_title", "data_accs_notes", "sampling_procedure", "title", "revision_id", "identifiability", "date_range_start", "date_range_end", "process_status"}, {"external_access_level", "unit_of_measurement", "license_title", "maintainer", "relationships_as_object", "geog_coverage", "private", "maintainer_email", "num_tags", "keywords", "admin_notes", "id", "metadata_created", "archived", "metadata_modified", "author", "author_email", "data_sensitivity", "state", "version", "data_collector", "creator_user_id", "type", "weight_notes", "resources", "data_collection_notes", "num_resources", "data_collection_technique", "tags", "clean_ops_notes", "visibility", "operational_purpose_of_data", "original_id", "groups", "license_id", "response_rate_notes", "relationships_as_subject", "organization", "name", "isopen", "sampling_procedure_notes", "url", "notes", "owner_org", "short_title", "data_accs_notes", "sampling_procedure", "title", "revision_id", "identifiability", "date_range_start", "date_range_end", "process_status"}),
     #"Extracted Values" = Table.TransformColumns(#"Expanded Column1", {"sampling_procedure", each Text.Combine(List.Transform(_, Text.From)), type text}),
    #"Expanded organization" = Table.ExpandRecordColumn(#"Extracted Values", "organization", {"title"}, {"organization.title"}),
    #"Expanded operational_purpose_of_data" = Table.ExpandListColumn(#"Expanded organization", "operational_purpose_of_data"),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded operational_purpose_of_data",{{"metadata_created", type datetime}, {"date_range_start", type date}, {"date_range_end", type date}, {"metadata_modified", type datetime}})
in
    #"Expanded operational_purpose_of_data"

**Comment by avdata99** [comment]
Perfect @mariannurban I'll che this

**Comment by avdata99** [comment]
I'm seeing differences in the counters

![image](https://user-images.githubusercontent.com/3237309/190627917-fa044c6f-35a3-4158-af06-2bb1db59576a.png)

**Comment by mariannurban** [comment]
Found something in the Excel sheet I'm using: this dataset is listed 3 times in my Excel, possibly because it has 3 values for Operational purpose of data. Could you check for me if it comes from the API 3 times as well? 
![image](https://user-images.githubusercontent.com/3184712/196104348-392014aa-978c-443f-80ae-f72372d60cec.png)

**Comment by avdata99** [comment]
Hi Mariann, I found the difference

The user interface is not including the deposited datasets
I've found the change. Chris applied this on Mar 25, 2021 due to a request
to hide them.
The API shows those deposited datasets

Should we hide them from the API?
Should we display them in the UI?
Or should we leave it as it is?

Cheers,

Andrés Vázquez Flexes

Software developer

Open Knowledge Foundation <http://okfn.org/> - For a fair, free and open
future

http://okfn.org | @okfn <http://twitter.com/OKFN> | Facebook
<https://www.facebook.com/OKFNetwork> | Blog <http://blog.okfn.org/>

**Comment by avdata99** [comment]
This is a expected difference. Tests added.
We can change this behavior if required
