### ISSUE TITLE
A rejected partner user is trying to request an account again

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#886]
Hi @avdata99 ,

could you check on this email address in the DB, please? One partner account request has been rejected for sure, I think he should be able to request one again, with the same email...?

![image](https://user-images.githubusercontent.com/3184712/193001862-dcc96717-5d6b-4ba0-a113-78aba1435888.png)

**Comment by avdata99** [comment]
Closed with #889
