### ISSUE TITLE
UAT homepage text is different than on prod

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#911]
Not sure when this happened or if this is an issue, but UAT homepage is like this:
![image](https://user-images.githubusercontent.com/3184712/200814914-847d29c3-0e7e-4404-8cff-7cb9d6cb97d7.png)
 The text on prod normally is: 
"  
 The Raw Internal Data Library is UNHCR’s secure globally-supported space for indexing, versioning and storing data that is collected or managed outside of the corporate data systems.
Keeping and reusing raw data is important to create baselines for indicators and population data, new analytical products, updating maps, monitoring partner data management capacity, developing targeting models, cleaning data, and auditing previous analysis results. This includes most of UNHCR’s protection assessment and monitoring data, as there are no corporate systems for anonymized or personally identifiable operational microdata.

RIDL supports datasets that are still changing and being versioned, in addition to those that are final and will no longer be changed and can be considered the “official” versions for a particular information management project.

More guidance on how to use RIDL is available here."

**Comment by avdata99** [comment]
@mariannurban the text for the Home page could be defined in the site's config
If nothing is defined for **Intro Text** (like production), we'll see a default text

![image](https://user-images.githubusercontent.com/3237309/200823202-f10a6ec6-07fc-4a32-9810-719994c9ce7c.png)

If an **Intro text** is defined (like UAT), we'll show this custom text in the home page.

![image](https://user-images.githubusercontent.com/3237309/200823653-2ede93a8-2c42-418e-a104-a564e21ecf95.png)

If we clean the **Intro text** config value for UAT, both environments will show the same text.
