### ISSUE TITLE
Prod: file attachment upload results in 403 Forbidden

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#915]
![image](https://user-images.githubusercontent.com/3184712/200883621-6a4205fe-8cf4-4942-a21c-8f3099b4ee7c.png)

[MCNA II 2015 Report.pdf](https://github.com/okfn/ckanext-unhcr/files/9972999/MCNA.II.2015.Report.pdf)

Tried to upload it to https://ridl.unhcr.org/dataset/multi-cluster-need-assessment-ii-2015

with metadata 
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/3184712/200883866-cb31838b-07e6-4150-aff8-1453683eae29.png)

@avdata99

**Comment by avdata99** [comment]
There is no reason for this error.
This is probably related with AWS @mariannurban 
Can you ask the WAF team about this error?

**Comment by mariannurban** [comment]
@avdata99 AWS in general or do you think this is a WAF issue?

**Comment by avdata99** [comment]
I assume it's a WAF issue @mariannurban.

**Comment by avdata99** [comment]
Closing since the dataset already include the resource
