### ISSUE TITLE
Error showing map in dataset

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#924]
Some datasets are not properly show map with geometries. 
[Example](https://ridl-uat.unhcr.org/dataset/syr-registration-data-2022-06):

![image](https://user-images.githubusercontent.com/3237309/203799202-43cc3d3a-8309-49ef-8e45-e29ed2a1032f.png)

**Comment by amercader** [comment]
Looks like the geometries are empty:

![Screenshot from 2022-11-24 15-53-03](https://user-images.githubusercontent.com/200230/203813097-70f14b68-d3ac-4d2b-bf5d-faf74d71d89c.png)
