### ISSUE TITLE
PDF resource is not loading properly

### ISSUE THREAD

**Issue by mariannurban** [okfn/ckanext-unhcr#948]
Hi @avdata99 ,

would you mind checking on this file attachment? Something really funky is happening when the content loads... https://ridl.unhcr.org/dataset/multi-sector-needs-assesment-warsaw-poland-2022/resource/db9c80f2-6b5d-4961-ba64-c2911dd390b1

**Comment by avdata99** [comment]
I'm looking at it @mariannurban, thanks

**Comment by avdata99** [comment]
@mariannurban, the error is that the user forgot to upload the resource file. If the user upload the PDF file, this will be ok.

I'll fix to properly display this error and avoid users to create resources without files.
